version: '3'

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  db:
    driver: local

services:

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - db:/var/lib/mysql

  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./templates:/data/gitea/templates
      - ./public:/data/gitea/public
      - ./conf:/data/gitea/conf
      - ./img:/data/gitea/conf
    ports:
      - '3000:3000'
      - '222:22'
    depends_on:
      - db