version: '3'

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  db:
    driver: local

services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - db:/var/lib/mysql

  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../gitea/templates:/data/gitea/templates
      - ../gitea/public:/data/gitea/public
      - ../gitea/conf:/data/gitea/conf
      - ../gitea/img:/data/gitea/conf
    ports:
      - '3000:3000'
      - '22:22'
    depends_on:
      - db

  strapi:
    tty: true
    container_name: strapi
    image: node:18-alpine
    working_dir: /srv/strapi
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=gitea
    networks:
      - gitea
    volumes:
      - ../strapi:/srv/strapi
    ports:
      - '1337:1337'
    depends_on:
      - db